<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\ConsigneeDTO.cs" />
    <Compile Remove="Models\ConsigneeUnitDTO.cs" />
    <Compile Remove="Models\ResponseModel.cs" />
    <Compile Remove="Models\SystemInitDTO.cs" />
    <Compile Remove="Models\UserDTO.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CNET_V7_Domain">
      <HintPath>..\..\..\..\..\DLL\CNET_V7_Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
