namespace ERP.V7.WebPMS.Components.Pages.Profile.Shared;

public class CountryNationality
{
    public string Country { get; set; } = "";
    public string Nationality { get; set; } = "";
}

public static class NationalityLookup
{
    public static readonly List<CountryNationality> Items = new()
    {
        new() { Country = "Afghanistan", Nationality = "Afghan" },
        new() { Country = "Albania", Nationality = "Albanian" },
        new() { Country = "Algeria", Nationality = "Algerian" },
        new() { Country = "Angola", Nationality = "Angolan" },
        new() { Country = "Argentina", Nationality = "Argentinean" },
        new() { Country = "Armenia", Nationality = "Armenian" },
        new() { Country = "Australia", Nationality = "Australian" },
        new() { Country = "Austria", Nationality = "Austrian" },
        new() { Country = "Azerbaijan", Nationality = "Azerbaijani" },
        new() { Country = "Bahrain", Nationality = "Bahraini" },
        new() { Country = "Bangladesh", Nationality = "Bangladeshi" },
        new() { Country = "Belarus", Nationality = "Belarusian" },
        new() { Country = "Belgium", Nationality = "Belgian" },
        new() { Country = "Benin", Nationality = "Beninese" },
        new() { Country = "Bolivia", Nationality = "Bolivian" },
        new() { Country = "Bosnia and Herzegovina", Nationality = "Bosnian" },
        new() { Country = "Botswana", Nationality = "Motswana" },
        new() { Country = "Brazil", Nationality = "Brazilian" },
        new() { Country = "Bulgaria", Nationality = "Bulgarian" },
        new() { Country = "Burkina Faso", Nationality = "Burkinabe" },
        new() { Country = "Burundi", Nationality = "Burundian" },
        new() { Country = "Cambodia", Nationality = "Cambodian" },
        new() { Country = "Cameroon", Nationality = "Cameroonian" },
        new() { Country = "Canada", Nationality = "Canadian" },
        new() { Country = "Chad", Nationality = "Chadian" },
        new() { Country = "Chile", Nationality = "Chilean" },
        new() { Country = "China", Nationality = "Chinese" },
        new() { Country = "Colombia", Nationality = "Colombian" },
        new() { Country = "Congo (DRC)", Nationality = "Congolese" },
        new() { Country = "Costa Rica", Nationality = "Costa Rican" },
        new() { Country = "Croatia", Nationality = "Croatian" },
        new() { Country = "Cuba", Nationality = "Cuban" },
        new() { Country = "Cyprus", Nationality = "Cypriot" },
        new() { Country = "Czech Republic", Nationality = "Czech" },
        new() { Country = "Denmark", Nationality = "Danish" },
        new() { Country = "Djibouti", Nationality = "Djiboutian" },
        new() { Country = "Dominican Republic", Nationality = "Dominican" },
        new() { Country = "Ecuador", Nationality = "Ecuadorian" },
        new() { Country = "Egypt", Nationality = "Egyptian" },
        new() { Country = "El Salvador", Nationality = "Salvadoran" },
        new() { Country = "Eritrea", Nationality = "Eritrean" },
        new() { Country = "Estonia", Nationality = "Estonian" },
        new() { Country = "Eswatini", Nationality = "Swazi" },
        new() { Country = "Ethiopia", Nationality = "Ethiopian" },
        new() { Country = "Finland", Nationality = "Finnish" },
        new() { Country = "France", Nationality = "French" },
        new() { Country = "Gabon", Nationality = "Gabonese" },
        new() { Country = "Gambia", Nationality = "Gambian" },
        new() { Country = "Georgia", Nationality = "Georgian" },
        new() { Country = "Germany", Nationality = "German" },
        new() { Country = "Ghana", Nationality = "Ghanaian" },
        new() { Country = "Greece", Nationality = "Greek" },
        new() { Country = "Guatemala", Nationality = "Guatemalan" },
        new() { Country = "Guinea", Nationality = "Guinean" },
        new() { Country = "Haiti", Nationality = "Haitian" },
        new() { Country = "Honduras", Nationality = "Honduran" },
        new() { Country = "Hungary", Nationality = "Hungarian" },
        new() { Country = "Iceland", Nationality = "Icelandic" },
        new() { Country = "India", Nationality = "Indian" },
        new() { Country = "Indonesia", Nationality = "Indonesian" },
        new() { Country = "Iran", Nationality = "Iranian" },
        new() { Country = "Iraq", Nationality = "Iraqi" },
        new() { Country = "Ireland", Nationality = "Irish" },
        new() { Country = "Israel", Nationality = "Israeli" },
        new() { Country = "Italy", Nationality = "Italian" },
        new() { Country = "Ivory Coast", Nationality = "Ivorian" },
        new() { Country = "Jamaica", Nationality = "Jamaican" },
        new() { Country = "Japan", Nationality = "Japanese" },
        new() { Country = "Jordan", Nationality = "Jordanian" },
        new() { Country = "Kazakhstan", Nationality = "Kazakhstani" },
        new() { Country = "Kenya", Nationality = "Kenyan" },
        new() { Country = "Kuwait", Nationality = "Kuwaiti" },
        new() { Country = "Laos", Nationality = "Laotian" },
        new() { Country = "Latvia", Nationality = "Latvian" },
        new() { Country = "Lebanon", Nationality = "Lebanese" },
        new() { Country = "Lesotho", Nationality = "Mosotho" },
        new() { Country = "Liberia", Nationality = "Liberian" },
        new() { Country = "Libya", Nationality = "Libyan" },
        new() { Country = "Lithuania", Nationality = "Lithuanian" },
        new() { Country = "Luxembourg", Nationality = "Luxembourgish" },
        new() { Country = "Madagascar", Nationality = "Malagasy" },
        new() { Country = "Malawi", Nationality = "Malawian" },
        new() { Country = "Malaysia", Nationality = "Malaysian" },
        new() { Country = "Mali", Nationality = "Malian" },
        new() { Country = "Malta", Nationality = "Maltese" },
        new() { Country = "Mauritania", Nationality = "Mauritanian" },
        new() { Country = "Mauritius", Nationality = "Mauritian" },
        new() { Country = "Mexico", Nationality = "Mexican" },
        new() { Country = "Moldova", Nationality = "Moldovan" },
        new() { Country = "Mongolia", Nationality = "Mongolian" },
        new() { Country = "Montenegro", Nationality = "Montenegrin" },
        new() { Country = "Morocco", Nationality = "Moroccan" },
        new() { Country = "Mozambique", Nationality = "Mozambican" },
        new() { Country = "Myanmar", Nationality = "Burmese" },
        new() { Country = "Namibia", Nationality = "Namibian" },
        new() { Country = "Nepal", Nationality = "Nepalese" },
        new() { Country = "Netherlands", Nationality = "Dutch" },
        new() { Country = "New Zealand", Nationality = "New Zealander" },
        new() { Country = "Nicaragua", Nationality = "Nicaraguan" },
        new() { Country = "Niger", Nationality = "Nigerien" },
        new() { Country = "Nigeria", Nationality = "Nigerian" },
        new() { Country = "North Korea", Nationality = "North Korean" },
        new() { Country = "North Macedonia", Nationality = "Macedonian" },
        new() { Country = "Norway", Nationality = "Norwegian" },
        new() { Country = "Oman", Nationality = "Omani" },
        new() { Country = "Pakistan", Nationality = "Pakistani" },
        new() { Country = "Panama", Nationality = "Panamanian" },
        new() { Country = "Paraguay", Nationality = "Paraguayan" },
        new() { Country = "Peru", Nationality = "Peruvian" },
        new() { Country = "Philippines", Nationality = "Filipino" },
        new() { Country = "Poland", Nationality = "Polish" },
        new() { Country = "Portugal", Nationality = "Portuguese" },
        new() { Country = "Qatar", Nationality = "Qatari" },
        new() { Country = "Romania", Nationality = "Romanian" },
        new() { Country = "Russia", Nationality = "Russian" },
        new() { Country = "Rwanda", Nationality = "Rwandan" },
        new() { Country = "Saudi Arabia", Nationality = "Saudi" },
        new() { Country = "Senegal", Nationality = "Senegalese" },
        new() { Country = "Serbia", Nationality = "Serbian" },
        new() { Country = "Sierra Leone", Nationality = "Sierra Leonean" },
        new() { Country = "Singapore", Nationality = "Singaporean" },
        new() { Country = "Slovakia", Nationality = "Slovak" },
        new() { Country = "Slovenia", Nationality = "Slovenian" },
        new() { Country = "Somalia", Nationality = "Somali" },
        new() { Country = "South Africa", Nationality = "South African" },
        new() { Country = "South Korea", Nationality = "South Korean" },
        new() { Country = "South Sudan", Nationality = "South Sudanese" },
        new() { Country = "Spain", Nationality = "Spanish" },
        new() { Country = "Sri Lanka", Nationality = "Sri Lankan" },
        new() { Country = "Sudan", Nationality = "Sudanese" },
        new() { Country = "Sweden", Nationality = "Swedish" },
        new() { Country = "Switzerland", Nationality = "Swiss" },
        new() { Country = "Syria", Nationality = "Syrian" },
        new() { Country = "Taiwan", Nationality = "Taiwanese" },
        new() { Country = "Tanzania", Nationality = "Tanzanian" },
        new() { Country = "Thailand", Nationality = "Thai" },
        new() { Country = "Togo", Nationality = "Togolese" },
        new() { Country = "Tunisia", Nationality = "Tunisian" },
        new() { Country = "Turkey", Nationality = "Turkish" },
        new() { Country = "Uganda", Nationality = "Ugandan" },
        new() { Country = "Ukraine", Nationality = "Ukrainian" },
        new() { Country = "United Arab Emirates", Nationality = "Emirati" },
        new() { Country = "United Kingdom", Nationality = "British" },
        new() { Country = "United States", Nationality = "American" },
        new() { Country = "Uruguay", Nationality = "Uruguayan" },
        new() { Country = "Uzbekistan", Nationality = "Uzbekistani" },
        new() { Country = "Venezuela", Nationality = "Venezuelan" },
        new() { Country = "Vietnam", Nationality = "Vietnamese" },
        new() { Country = "Yemen", Nationality = "Yemeni" },
        new() { Country = "Zambia", Nationality = "Zambian" },
        new() { Country = "Zimbabwe", Nationality = "Zimbabwean" },
    };
}
